{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: clang-helpers
  #: .. versionchanged:: 0.6
  version: {{ GIT_VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  #: .. versionadded:: 0.6
  noarch: python
  #: .. versionadded:: 0.6
  #: .. versionchanged:: 0.6.1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - clang
    #: .. versionadded:: X.X.X
    - pandas
    - future
    - path_helpers
    - pydash
    - python
    #: .. versionadded:: X.X.X
    - six

  run:
    #: .. versionadded:: X.X.X
    - pandas
    - python
    - clang
    - path_helpers
    - pydash
    #: .. versionadded:: X.X.X
    - six

about:
  home: http://github.com/wheeler-microfluidics/clang-helpers
  license: MIT
